# numpy array operations


In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(f"Basic slicing: {arr[2:7]}")
print(f"Basic slicing with steps: {arr[1:8:2]}")
print(f"Negative indexing: {arr[-2]}")


Basic slicing: [3 4 5 6 7]
Basic slicing with steps: [2 4 6 8]
Negative indexing: 8


In [14]:
arr_2d=np.array([[1,2,3],  #row and column starts from 0 like 0th row, 1st row, 2nd row,... and similarly for columns
                 [4,5,6],
                 [7,8,9]])
print(f"Element at 1nd row and 2rd column: {(arr_2d[1, 2])}")
print("Entire row 1: ", arr_2d[1]) #print all elements of row 1
print("Entire column 2: ", arr_2d[:, 2]) #PRINT ALL ELEMENTS OF COLUMN 2

Element at 1nd row and 2rd column: 6
Entire row 1:  [4 5 6]
Entire column 2:  [3 6 9]


# sorting

In [ ]:
unsorted_arr=np.array([1,7,2,9,3,4,6,5])
print("Sorted array: ", np.sort(unsorted_arr))
unsorted_arr2d=np.array([[7,1],[9,2],[3,4],[6,5]])
print("sorted 2d array: \n", np.sort(unsorted_arr2d, axis=0)) #sort column wise
print("sorted 2d array: \n", np.sort(unsorted_arr2d, axis=1)) #sort row wise

Sorted array:  [1 2 3 4 5 6 7 9]
sorted 2d array: 
 [[3 1]
 [6 2]
 [7 4]
 [9 5]]
sorted 2d array: 
 [[1 7]
 [2 9]
 [3 4]
 [5 6]]


# filter

In [26]:
#even numbers print
num = np.array([1,2,3,4,5,6,7,8,9])
print("Even numbers: ", num[num%2==0])
indices=[0,2,5]
print("fancy indexing: ",num[indices])

Even numbers:  [2 4 6 8]
fancy indexing:  [1 3 6]


# filter with mask

In [24]:
mask = num > 5
print("Numbers greater than 5: ", num[mask])

Numbers greater than 5:  [6 7 8 9]


# fancy indexing vs np.where()

In [30]:
indices = [1,3,5]
print("array elements at indices: ", num[indices])
where_rrsult=np.where(num>5)
print("np Where method: ", num[where_rrsult])

array elements at indices:  [2 4 6]
np Where method:  [6 7 8 9]


In [36]:
condition_arr = np.where(num>5, num**2, num)
print("Condition_arr: ", condition_arr)

Condition_arr:  [ 1  2  3  4  5 36 49 64 81]


# adding and removing data

In [39]:
#concatinate 2 arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("concatinated array: ", np.concatenate((arr1, arr2)))
new_arr=np.delete(arr1, 1)
print("array after delete element from index 1: ", new_arr)

concatinated array:  [1 2 3 4 5 6]
array after delete element from index 1:  [1 3]


# array compatibility


In [42]:
a = np.array([1,2,3])
b= np.array([4,5,6,7])
print("compatibility check: ", a.shape==b.shape)

compatibility check:  False


In [49]:
arr=np.array([[1,2],[3,4]])
newrow=np.array([7,9])
newcol=np.array([[5],[8]])
addrow=np.vstack((arr, newrow))
addcol=np.hstack((arr, newcol))
print("array after adding a new row: \n", addrow)
print("array after adding a new column: \n", addcol)

array after adding a new row: 
 [[1 2]
 [3 4]
 [7 9]]
array after adding a new column: 
 [[1 2 5]
 [3 4 8]]
