# Learning array and basics
learning numpy

In [1]:
import numpy as np

# creating numpy array

In [3]:
arr_1d = np.array([1,2,3])
print("array 1d: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("array 2d: ", arr_2d)

array 1d:  [1 2 3]
array 2d:  [[1 2 3]
 [4 5 6]]


## diff. b/w lists & numpy array

In [12]:
py_list = [1,2,3]
print("python list multiplication: ", py_list *2) # just duplicate the list

nump_arr = np.array([1,2,3]) #multiply each element in the array with 2
print("numpy array multiplication: ", nump_arr *2)

python list multiplication:  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]


In [13]:
import time
start = time.time()
N= 10**7
py_list = [i*2 for i in range(N)]
print("python list multiplication time: ", time.time()-start)

start = time.time()
nump_arr = np.arange(N)*2
print("\nnumpy array multiplication time: ", time.time()-start)

python list multiplication time:  0.36351561546325684

numpy array multiplication time:  0.03212785720825195


# Creating array from scratch 

In [ ]:
zeros = np.zeros((3, 4)) #3 rows and 4 columns
print("zeros array : \n", zeros)

ones = np.ones((2, 3)) #2 rows & 3 columns
print("\nones array : \n", ones)

full = np.full((3, 3), 7) # a 3 x 3 matrices or array in which all elements are 7
print("\nfull array : \n", full)

random = np.random.random((4, 3)) #random matrix or array of 4x3 and random values lies b/w 0 to 1
print("\nrandom array: \n", random)


random = np.random.randint(1, 10, (4, 3)) #random matrix or array of 4x3 and random values lies b/w 0 to 1 & to get whole uses randint where the numbers or elemnts lies b/w 1 to 9
print("\nrandom array: \n", random)

seq = np.arange(1, 10, 2) # 2 is the steps
print("\nsequence array is:\n", seq)



zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]

full array : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

random array: 
 [[0.20418095 0.01959325 0.62230353]
 [0.75867502 0.07616034 0.47589856]
 [0.14250707 0.48313093 0.22306877]
 [0.04270969 0.06525018 0.99163506]]

random array: 
 [[2 5 3]
 [9 7 6]
 [4 3 3]
 [1 7 4]]

sequence is:
 [1 3 5 7 9]


# vector, matrix and tensor

In [31]:
#for vector = np.array([1,2,3])
vector = np.array([1,2,3])
print("\n Vector: \n", vector)

#for matrix = np.array([[1,2,3], [4,5,6]])
matrix = np.array([[1,2,3], [4,5,6]])
print("\n Matrix: \n", matrix)

#for tensor = np.array([[[1,2,], [3,4], [5,6]]])
tensor = np.array([[[1,2,], [3,4], [5,6]]])
print("\n Tensor: \n", tensor)


 Vector: 
 [1 2 3]

 Matrix: 
 [[1 2 3]
 [4 5 6]]

 Tensor: 
 [[[1 2]
  [3 4]
  [5 6]]]


# array properties

In [35]:
#properties:
#shape of array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape: ", arr.shape)
#dimension of array:
print("\ndimension: ", arr.ndim)
#size of array:
print("\nsize: ", arr.size)
#data type of array:
print("\ndata type: ", arr.dtype)

shape:  (2, 3)

dimension:  2

size:  6

data type:  int64


# array reshaping

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Original array: \n", arr)

reshaped = arr.reshape((3, 3)) #convert original array(arr) into 3x3 array or matrices
print("rrshaped array: \n", reshaped)


flat = arr.flatten() #convert reshaped array into a singlr row array like the original array(arr)
print("flatten array: \n", flat)

#ravel() → Returns a view (changes in ravelled array may affect the original).

#flatten() → Always returns a copy (independent from original).

ravel= reshaped.ravel()
print("Raveled array:\n", ravel)

transpose = reshaped.T #transpose of array or matrix(here we use reshaped.T, so we get transpose of reshaped array or matrix) 
print("transpose: \n", transpose)

Original array: 
 [1 2 3 4 5 6 7 8 9]
rrshaped array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
flatten array: 
 [1 2 3 4 5 6 7 8 9]
Raveled array:
 [1 2 3 4 5 6 7 8 9]
transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
